name: yt-dlp

on:
  push:
    branches: [ "main" ]  # 当代码推送到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: .
        
    permissions:
      contents: read
      packages: write     # 必须有写入包的权限

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: denoland/setup-deno@v2
        with:
          deno-version: lts
          
      - uses: FedericoCarboni/setup-ffmpeg@v3
        id: setup-ffmpeg
        with:
          # A specific version to download, may also be "release" or a specific version
          # like "6.1.0". At the moment semver specifiers (i.e. >=6.1.0) are supported
          # only on Windows, on other platforms they are allowed but version is matched
          # exactly regardless.
          ffmpeg-version: release
          # Target architecture of the ffmpeg executable to install. Defaults to the
          # system architecture. Only x64 and arm64 are supported (arm64 only on Linux).
          architecture: ''
          # Linking type of the binaries. Use "shared" to download shared binaries and 
          # "static" for statically linked ones. Shared builds are currently only available
          # for windows releases. Defaults to "static"
          linking-type: static
          # As of version 3 of this action, builds are no longer downloaded from GitHub
          # except on Windows: https://github.com/GyanD/codexffmpeg/releases.
          github-token: ${{ github.server_url == 'https://github.com' && github.token || '' }}

      - name: Download yt-dlp
        uses: robinraju/release-downloader@v1
        with:
          repository: 'yt-dlp/yt-dlp'
          latest: true
          fileName: 'yt-dlp_linux'

      - name: Upload cookies.txt to here
        env:
          SRCE: "${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_DIR }}/cookies.txt"
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -P ${{ secrets.REMOTE_PORT }} $SRCE ./cookies.txt
      
      - name: Make the script files executable
        run: chmod +x my-script.sh yt-dlp_linux

      - name: Run the scripts
        run: ./my-script.sh

      - name: rm the scripts
        run: rm ./my-script.sh

      - name: Send rest thing to remote
        env:
          DEST: "${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_DIR }}/"
        run: |
          rsync -avP -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -c chacha20-poly1305@openssh.com" ./* $DEST

        
